version: "3.7"
services: 
  ppos:
    image: diegofgm/martins:ppos2.0
    environment:
 10.1.0.22
      STATIC_IP: 10.1.0.23
      STATIC_IP: 10.1.0.24
      STATIC_IP: 10.1.0.25
      STATIC_IP: 10.1.0.26
      STATIC_IP: 10.1.0.27
      STATIC_IP: 10.1.0.28
      STATIC_IP: 10.1.0.29
      STATIC_IP: 10.1.0.30
      STATIC_IP: 10.1.0.31
      STATIC_IP: 10.1.0.32
      STATIC_IP: 10.1.0.33
      STATIC_IP: 10.1.0.34
      STATIC_IP: 10.1.0.35
      STATIC_IP: 10.1.0.36
      STATIC_IP: 10.1.0.37
      STATIC_IP: 10.1.0.38
      STATIC_IP: 10.1.0.39
      STATIC_IP: 10.1.0.40
      STATIC_IP: 10.1.0.41
      STATIC_IP: 10.1.0.42
      STATIC_IP: 10.1.0.43
      STATIC_IP: 10.1.0.44
      STATIC_IP: 10.1.0.45
      STATIC_IP: 10.1.0.46
    STATIC_IP: 10.1.0.47
      STATIC_IP: 10.1.0.48
      STATIC_IP: 10.1.0.49
      STATIC_IP: 10.1.0.50
      STATIC_IP: 10.1.0.51
      STATIC_IP: 10.1.0.52
      STATIC_IP: 10.1.0.53
      STATIC_IP: 10.1.0.54
      STATIC_IP: 10.1.0.55
      STATIC_IP: 10.1.0.56
      STATIC_IP: 10.1.0.57
      STATIC_IP: 10.1.0.58
      STATIC_IP: 10.1.0.59
      STATIC_IP: 10.1.0.60
      STATIC_IP: 10.1.0.61
      STATIC_IP: 10.1.0.62
      STATIC_IP: 10.1.0.63
      STATIC_IP: 10.1.0.64
      STATIC_IP: 10.1.0.65
      STATIC_IP: 10.1.0.66
      STATIC_IP: 10.1.0.67
      STATIC_IP: 10.1.0.68
      STATIC_IP: 10.1.0.69
      STATIC_IP: 10.1.0.70
      STATIC_IP: 10.1.0.71
      STATIC_IP: 10.1.0.72
      STATIC_IP: 10.1.0.73
      STATIC_IP: 10.1.0.74
      STATIC_IP: 10.1.0.75
      STATIC_IP: 10.1.0.76
      STATIC_IP: 10.1.0.77
      STATIC_IP: 10.1.0.78
      STATIC_IP: 10.1.0.79
      STATIC_IP: 10.1.0.80
      STATIC_IP: 10.1.0.81
      STATIC_IP: 10.1.0.82
      STATIC_IP: 10.1.0.83
      STATIC_IP: 10.1.0.84
      STATIC_IP: 10.1.0.85
      STATIC_IP: 10.1.0.86
      STATIC_IP: 10.1.0.87
      STATIC_IP: 10.1.0.88
      STATIC_IP: 10.1.0.89
      STATIC_IP: 10.1.0.90
      STATIC_IP: 10.1.0.91
      STATIC_IP: 10.1.0.92
      STATIC_IP: 10.1.0.93
      STATIC_IP: 10.1.0.94
      STATIC_IP: 10.1.0.95
      STATIC_IP: 10.1.0.96
      STATIC_IP: 10.1.0.97
      STATIC_IP: 10.1.0.98
      STATIC_IP: 10.1.0.99
      STATIC_IP: 10.1.0.100
      STATIC_IP: 10.1.0.101
      STATIC_IP: 10.1.0.102
      STATIC_IP: 10.1.0.103
      STATIC_IP: 10.1.0.104
      STATIC_IP: 10.1.0.105
      STATIC_IP: 10.1.0.106
      STATIC_IP: 10.1.0.107
      STATIC_IP: 10.1.0.108
      STATIC_IP: 10.1.0.109
      STATIC_IP: 10.1.0.110
      STATIC_IP: 10.1.0.111
      STATIC_IP: 10.1.0.112
      STATIC_IP: 10.1.0.113
      STATIC_IP: 10.1.0.114
      STATIC_IP: 10.1.0.115
      STATIC_IP: 10.1.0.116
      STATIC_IP: 10.1.0.117
      STATIC_IP: 10.1.0.118
      STATIC_IP: 10.1.0.119
      STATIC_IP: 10.1.0.120
      STATIC_IP: 10.1.0.121
      STATIC_IP: 10.1.0.122
      STATIC_IP: 10.1.0.123
      STATIC_IP: 10.1.0.124
      STATIC_IP: 10.1.0.125
      STATIC_IP: 10.1.0.126
      STATIC_IP: 10.1.0.127
      STATIC_IP: 10.1.0.128
      STATIC_IP: 10.1.0.129
      STATIC_IP: 10.1.0.130
      STATIC_IP: 10.1.0.131
      STATIC_IP: 10.1.0.132
      STATIC_IP: 10.1.0.133
      STATIC_IP: 10.1.0.134
      STATIC_IP: 10.1.0.135
      STATIC_IP: 10.1.0.136
      STATIC_IP: 10.1.0.137
      STATIC_IP: 10.1.0.138
      STATIC_IP: 10.1.0.139
      STATIC_IP: 10.1.0.140
      STATIC_IP: 10.1.0.141
      STATIC_IP: 10.1.0.142
      STATIC_IP: 10.1.0.143
      STATIC_IP: 10.1.0.144
      STATIC_IP: 10.1.0.145
      STATIC_IP: 10.1.0.146
      STATIC_IP: 10.1.0.147
      STATIC_IP: 10.1.0.148
      STATIC_IP: 10.1.0.149
      STATIC_IP: 10.1.0.150
      STATIC_IP: 10.1.0.151
      STATIC_IP: 10.1.0.152
      STATIC_IP: 10.1.0.153
      STATIC_IP: 10.1.0.154
      STATIC_IP: 10.1.0.155
      STATIC_IP: 10.1.0.156
      STATIC_IP: 10.1.0.157
      STATIC_IP: 10.1.0.158
      STATIC_IP: 10.1.0.159
      STATIC_IP: 10.1.0.160
      STATIC_IP: 10.1.0.161
      STATIC_IP: 10.1.0.162
      STATIC_IP: 10.1.0.163
      STATIC_IP: 10.1.0.164
      STATIC_IP: 10.1.0.165
      STATIC_IP: 10.1.0.166
      STATIC_IP: 10.1.0.167
      STATIC_IP: 10.1.0.168
      STATIC_IP: 10.1.0.169
      STATIC_IP: 10.1.0.170
      STATIC_IP: 10.1.0.171
      STATIC_IP: 10.1.0.172
      STATIC_IP: 10.1.0.173
      STATIC_IP: 10.1.0.174
      STATIC_IP: 10.1.0.175
      STATIC_IP: 10.1.0.176
      STATIC_IP: 10.1.0.177
      STATIC_IP: 10.1.0.178
      STATIC_IP: 10.1.0.179
      STATIC_IP: 10.1.0.180
      STATIC_IP: 10.1.0.181
      STATIC_IP: 10.1.0.182
      STATIC_IP: 10.1.0.183
      STATIC_IP: 10.1.0.184
      STATIC_IP: 10.1.0.185
      STATIC_IP: 10.1.0.186
      STATIC_IP: 10.1.0.187
      STATIC_IP: 10.1.0.188
      STATIC_IP: 10.1.0.189
      STATIC_IP: 10.1.0.190
      STATIC_IP: 10.1.0.191
      STATIC_IP: 10.1.0.192
      STATIC_IP: 10.1.0.193
      STATIC_IP: 10.1.0.194
      STATIC_IP: 10.1.0.195
      STATIC_IP: 10.1.0.196
      STATIC_IP: 10.1.0.197
      STATIC_IP: 10.1.0.198
      STATIC_IP: 10.1.0.199
      STATIC_IP: 10.1.0.200
      STATIC_IP: 10.1.0.201
      STATIC_IP: 10.1.0.202
      STATIC_IP: 10.1.0.203
      STATIC_IP: 10.1.0.204
      STATIC_IP: 10.1.0.205
      STATIC_IP: 10.1.0.206
      STATIC_IP: 10.1.0.207
      STATIC_IP: 10.1.0.208
      STATIC_IP: 10.1.0.209
      STATIC_IP: 10.1.0.210
      STATIC_IP: 10.1.0.211
      STATIC_IP: 10.1.0.212
      STATIC_IP: 10.1.0.213
      STATIC_IP: 10.1.0.214
      STATIC_IP: 10.1.0.215
      STATIC_IP: 10.1.0.216
      STATIC_IP: 10.1.0.217
      STATIC_IP: 10.1.0.218
      STATIC_IP: 10.1.0.219
      STATIC_IP: 10.1.0.220
      STATIC_IP: 10.1.0.221
      STATIC_IP: 10.1.0.222
      STATIC_IP: 10.1.0.223
      STATIC_IP: 10.1.0.224
      STATIC_IP: 10.1.0.225
      STATIC_IP: 10.1.0.226
      STATIC_IP: 10.1.0.227
      STATIC_IP: 10.1.0.228
      STATIC_IP: 10.1.0.229
      STATIC_IP: 10.1.0.230
      STATIC_IP: 10.1.0.231
      STATIC_IP: 10.1.0.232
      STATIC_IP: 10.1.0.233
      STATIC_IP: 10.1.0.234
      STATIC_IP: 10.1.0.235
      STATIC_IP: 10.1.0.236
      STATIC_IP: 10.1.0.237
      STATIC_IP: 10.1.0.238
      STATIC_IP: 10.1.0.239
      STATIC_IP: 10.1.0.240
      STATIC_IP: 10.1.0.241
      STATIC_IP: 10.1.0.242
      STATIC_IP: 10.1.0.243
      STATIC_IP: 10.1.0.244
      STATIC_IP: 10.1.0.245
      STATIC_IP: 10.1.0.246
      STATIC_IP: 10.1.0.247
      STATIC_IP: 10.1.0.248
      STATIC_IP: 10.1.0.249
      STATIC_IP: 10.1.0.250
      STATIC_IP: 10.1.0.251
      STATIC_IP: 10.1.0.252
      STATIC_IP: 10.1.0.253
      STATIC_IP: 10.1.0.254
      STATIC_IP: 10.1.0.255
      STATIC_IP: 10.1.1.0
      STATIC_IP: 10.1.1.1
      STATIC_IP: 10.1.1.2
      STATIC_IP: 10.1.1.3
      STATIC_IP: 10.1.1.4
      STATIC_IP: 10.1.1.5
      STATIC_IP: 10.1.1.6
      STATIC_IP: 10.1.1.7
      STATIC_IP: 10.1.1.8
      STATIC_IP: 10.1.1.9
      STATIC_IP: 10.1.1.10
      STATIC_IP: 10.1.1.11
      STATIC_IP: 10.1.1.12
      STATIC_IP: 10.1.1.13
      STATIC_IP: 10.1.1.14
      STATIC_IP: 10.1.1.15
      STATIC_IP: 10.1.1.16
      STATIC_IP: 10.1.1.17
      STATIC_IP: 10.1.1.18
      STATIC_IP: 10.1.1.19
      STATIC_IP: 10.1.1.20
      STATIC_IP: 10.1.1.21
      STATIC_IP: 10.1.1.22
      STATIC_IP: 10.1.1.23
      STATIC_IP: 10.1.1.24
      STATIC_IP: 10.1.1.25
      STATIC_IP: 10.1.1.26
      STATIC_IP: 10.1.1.27
      STATIC_IP: 10.1.1.28
      STATIC_IP: 10.1.1.29
      STATIC_IP: 10.1.1.30
      STATIC_IP: 10.1.1.31
      STATIC_IP: 10.1.1.32
      STATIC_IP: 10.1.1.33
      STATIC_IP: 10.1.1.34
      STATIC_IP: 10.1.1.35
      STATIC_IP: 10.1.1.36
      STATIC_IP: 10.1.1.37
      STATIC_IP: 10.1.1.38
      STATIC_IP: 10.1.1.39
      STATIC_IP: 10.1.1.40
      STATIC_IP: 10.1.1.41
      STATIC_IP: 10.1.1.42
      STATIC_IP: 10.1.1.43
      STATIC_IP: 10.1.1.44
      STATIC_IP: 10.1.1.45
      STATIC_IP: 10.1.1.46
      STATIC_IP: 10.1.1.47
      STATIC_IP: 10.1.1.48
      STATIC_IP: 10.1.1.49
      STATIC_IP: 10.1.1.50
      STATIC_IP: 10.1.1.51
      STATIC_IP: 10.1.1.52
      STATIC_IP: 10.1.1.53
      STATIC_IP: 10.1.1.54
      STATIC_IP: 10.1.1.55
      STATIC_IP: 10.1.1.56
      STATIC_IP: 10.1.1.57
      STATIC_IP: 10.1.1.58
      STATIC_IP: 10.1.1.59
      STATIC_IP: 10.1.1.60
      STATIC_IP: 10.1.1.61
      STATIC_IP: 10.1.1.62
      STATIC_IP: 10.1.1.63
      STATIC_IP: 10.1.1.64
      STATIC_IP: 10.1.1.65
      STATIC_IP: 10.1.1.66
      STATIC_IP: 10.1.1.67
      STATIC_IP: 10.1.1.68
      STATIC_IP: 10.1.1.69
      STATIC_IP: 10.1.1.70
      STATIC_IP: 10.1.1.71
      STATIC_IP: 10.1.1.72
      STATIC_IP: 10.1.1.73
      STATIC_IP: 10.1.1.74
      STATIC_IP: 10.1.1.75
      STATIC_IP: 10.1.1.76
      STATIC_IP: 10.1.1.77
      STATIC_IP: 10.1.1.78
      STATIC_IP: 10.1.1.79
      STATIC_IP: 10.1.1.80
      STATIC_IP: 10.1.1.81
      STATIC_IP: 10.1.1.82
      STATIC_IP: 10.1.1.83
      STATIC_IP: 10.1.1.84
      STATIC_IP: 10.1.1.85
      STATIC_IP: 10.1.1.86
      STATIC_IP: 10.1.1.87
      STATIC_IP: 10.1.1.88
      STATIC_IP: 10.1.1.89
      STATIC_IP: 10.1.1.90
      STATIC_IP: 10.1.1.91
      STATIC_IP: 10.1.1.92
      STATIC_IP: 10.1.1.93
      STATIC_IP: 10.1.1.94
      STATIC_IP: 10.1.1.95
      STATIC_IP: 10.1.1.96
      STATIC_IP: 10.1.1.97
      STATIC_IP: 10.1.1.98
      STATIC_IP: 10.1.1.99
      STATIC_IP: 10.1.1.100
      STATIC_IP: 10.1.1.101
      STATIC_IP: 10.1.1.102
      STATIC_IP: 10.1.1.103
      STATIC_IP: 10.1.1.104
      STATIC_IP: 10.1.1.105
      STATIC_IP: 10.1.1.106
      STATIC_IP: 10.1.1.107
      STATIC_IP: 10.1.1.108
      STATIC_IP: 10.1.1.109
      STATIC_IP: 10.1.1.110
      STATIC_IP: 10.1.1.111
      STATIC_IP: 10.1.1.112
      STATIC_IP: 10.1.1.113
      STATIC_IP: 10.1.1.114
      STATIC_IP: 10.1.1.115
      STATIC_IP: 10.1.1.116
      STATIC_IP: 10.1.1.117
      STATIC_IP: 10.1.1.118
      STATIC_IP: 10.1.1.119
      STATIC_IP: 10.1.1.120
      STATIC_IP: 10.1.1.121
      STATIC_IP: 10.1.1.122
      STATIC_IP: 10.1.1.123
      STATIC_IP: 10.1.1.124
      STATIC_IP: 10.1.1.125
      STATIC_IP: 10.1.1.126
      STATIC_IP: 10.1.1.127
      STATIC_IP: 10.1.1.128
      STATIC_IP: 10.1.1.129
      STATIC_IP: 10.1.1.130
      STATIC_IP: 10.1.1.131
      STATIC_IP: 10.1.1.132
      STATIC_IP: 10.1.1.133
      STATIC_IP: 10.1.1.134
      STATIC_IP: 10.1.1.135
      STATIC_IP: 10.1.1.136
      STATIC_IP: 10.1.1.137
      STATIC_IP: 10.1.1.138
      STATIC_IP: 10.1.1.139
      STATIC_IP: 10.1.1.140
      STATIC_IP: 10.1.1.141
      STATIC_IP: 10.1.1.142
      STATIC_IP: 10.1.1.143
      STATIC_IP: 10.1.1.144
      STATIC_IP: 10.1.1.145
      STATIC_IP: 10.1.1.166
      STATIC_IP: 10.1.1.167
      STATIC_IP: 10.1.1.168
      STATIC_IP: 10.1.1.169
      STATIC_IP: 10.1.1.170
      STATIC_IP: 10.1.1.171
      STATIC_IP: 10.1.1.172
      STATIC_IP: 10.1.1.173
      STATIC_IP: 10.1.1.174
      STATIC_IP: 10.1.1.175
      STATIC_IP: 10.1.1.176
      STATIC_IP: 10.1.1.177
      STATIC_IP: 10.1.1.178
      STATIC_IP: 10.1.1.179
      STATIC_IP: 10.1.1.180
      STATIC_IP: 10.1.1.181
      STATIC_IP: 10.1.1.182
      STATIC_IP: 10.1.1.183
      STATIC_IP: 10.1.1.184
      STATIC_IP: 10.1.1.185
      STATIC_IP: 10.1.1.186
      STATIC_IP: 10.1.1.187
      STATIC_IP: 10.1.1.188
      STATIC_IP: 10.1.1.189
      STATIC_IP: 10.1.1.190
      STATIC_IP: 10.1.1.191
      STATIC_IP: 10.1.1.192
      STATIC_IP: 10.1.1.193
      STATIC_IP: 10.1.1.194
      STATIC_IP: 10.1.1.195
      STATIC_IP: 10.1.1.196
      STATIC_IP: 10.1.1.197
      STATIC_IP: 10.1.1.198
      STATIC_IP: 10.1.1.199
      STATIC_IP: 10.1.1.200
      STATIC_IP: 10.1.1.201
      STATIC_IP: 10.1.1.202
      STATIC_IP: 10.1.1.203
      STATIC_IP: 10.1.1.204
      STATIC_IP: 10.1.1.205
      STATIC_IP: 10.1.1.206
      STATIC_IP: 10.1.1.207
      STATIC_IP: 10.1.1.208
      STATIC_IP: 10.1.1.209
      STATIC_IP: 10.1.1.210
      STATIC_IP: 10.1.1.211
      STATIC_IP: 10.1.1.212
      STATIC_IP: 10.1.1.213
      STATIC_IP: 10.1.1.214
      STATIC_IP: 10.1.1.215
      STATIC_IP: 10.1.1.216
      STATIC_IP: 10.1.1.217
      STATIC_IP: 10.1.1.218
      STATIC_IP: 10.1.1.219
      STATIC_IP: 10.1.1.220
      STATIC_IP: 10.1.1.221
      STATIC_IP: 10.1.1.222
      STATIC_IP: 10.1.1.223
      STATIC_IP: 10.1.1.224
      STATIC_IP: 10.1.1.225
      STATIC_IP: 10.1.1.226
      STATIC_IP: 10.1.1.227
      STATIC_IP: 10.1.1.228
      STATIC_IP: 10.1.1.229
      STATIC_IP: 10.1.1.230
      STATIC_IP: 10.1.1.231
      STATIC_IP: 10.1.1.232
      STATIC_IP: 10.1.1.233
      STATIC_IP: 10.1.1.234
      STATIC_IP: 10.1.1.235
      STATIC_IP: 10.1.1.236
      STATIC_IP: 10.1.1.237
      STATIC_IP: 10.1.1.238
      STATIC_IP: 10.1.1.239
      STATIC_IP: 10.1.1.240
      STATIC_IP: 10.1.1.241
      STATIC_IP: 10.1.1.242
      STATIC_IP: 10.1.1.243
      STATIC_IP: 10.1.1.244
      STATIC_IP: 10.1.1.245
      STATIC_IP: 10.1.1.246
      STATIC_IP: 10.1.1.247
      STATIC_IP: 10.1.1.248
      STATIC_IP: 10.1.1.249
      STATIC_IP: 10.1.1.250
      STATIC_IP: 10.1.1.251
      STATIC_IP: 10.1.1.252
      STATIC_IP: 10.1.1.253
      STATIC_IP: 10.1.1.254
      STATIC_IP: 10.1.1.255
      STATIC_IP: 10.1.2.0
      STATIC_IP: 10.1.2.1
      STATIC_IP: 10.1.2.2
      STATIC_IP: 10.1.2.3
      STATIC_IP: 10.1.2.4
      STATIC_IP: 10.1.2.5
      STATIC_IP: 10.1.2.6
      STATIC_IP: 10.1.2.7
      STATIC_IP: 10.1.2.8
      STATIC_IP: 10.1.2.9
    networks:
      - netppos
    deploy:
      replicas: 500
      placement:
        constraints: [node.role != manager]
networks:
  netppos:
     external: True
